name: dmcgb
channels:
  - defaults
dependencies:
  - python=3.9
  - cudatoolkit=9.2
  - absl-py
  - pyparsing
  - pip
  - pip:
    - numpy==1.19.5
    - torch==1.7.1
    - torchvision==0.8.2
    - pillow
    - termcolor
    - imageio
    - imageio-ffmpeg
    - opencv-python
    - xmltodict
    - tqdm
    - einops
    - kornia
